esp_toml_version = 1.0
firmware_images_url = "https://dl.espressif.com/AE/Zumi-mini/"

supported_apps = ["Zumi-mini_Demo_EN_V0_3_0", "Zumi-mini_Demo_CN_V0_3_0", "Zumi-mini_USB_Headset_V0_0_1", "Zumi-mini_ChatGPT_Demo_V1_0"]

[Zumi-mini_Demo_EN_V0_3_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "Zumi-mini_Demo_EN_V0.3.0.bin"
android_app_url = ""
ios_app_url = ""

[Zumi-mini_Demo_CN_V0_3_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "Zumi-mini_Demo_CN_V0.3.0.bin"
android_app_url = ""
ios_app_url = ""

[Zumi-mini_USB_Headset_V0_0_1]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "Zumi-mini_USB_Headset_V0.0.1.bin"
android_app_url = ""
ios_app_url = ""

[Zumi-mini_ChatGPT_Demo_V1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "Zumi-mini_ChatGPT_Demo_V1.0.bin"
android_app_url = ""
ios_app_url = ""