esp_toml_version = 1.0

# URL to your firmware images directory
firmware_images_url = "https://truedo.github.io/zumimini/"

# List of supported apps
supported_apps = ["ZumiMini"]

[ZumiMini]
# Supported chipsets
chipsets = ["ESP32-S3"]

# Binary file paths and offsets for each chipset
image.esp32-s3 = "merged-flash.bin"

