esp_toml_version = 1.0

# URL to your firmware images directory
firmware_images_url = "https://github.com/truedo/RokitArduinoBasic/tree/master/zumi"

# List of supported apps
supported_apps = ["ZumiMini"]

# Optional: Application configuration markdown file URL
config_readme_url = "http://example.com/firmware/config_readme.md"

[ZumiMini]
# Supported chipsets
chipsets = ["ESP32-S3"]

# Binary file paths and offsets for each chipset
image.esp32-s3.bootloader = { file = "bootloader.bin", offset = "0x0000" }
image.esp32-s3.partition_table = { file = "partition-table.bin", offset = "0x8000" }
image.esp32-s3.application = { file = "ZumiMini_main.bin", offset = "0x10000" }

# Optional: Phone app URLs
android_app_url = ""
ios_app_url = ""

# Optional: Additional information markdown file URL
readme.text = "http://example.com/firmware/readme.md"

# Optional: Console baudrate (default is 115200)
console_baudrate = 921600
